name: Deploy to WordPress SVN

on:
  push:
    tags:
      - "*" # Löst bei jedem Tag-Push aus

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag name and commit message
        id: get_info
        run: |
          TAG_NAME=${GITHUB_REF_NAME}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

          MESSAGE=$(git log -1 --pretty=%B)
          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Install SVN
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Checkout WordPress SVN repo
        run: |
          svn checkout "${{ secrets.SVN_REPO }}" wordpress-svn \
            --username "${{ secrets.SVN_USERNAME }}" \
            --password "${{ secrets.SVN_PASSWORD }}" \
            --non-interactive --no-auth-cache

      - name: Copy plugin files to trunk
        run: |
          # Kopiere alle Plugin-Dateien in trunk/
          rsync -av --delete \
            --exclude=".git*" \
            --exclude=".github" \
            --exclude="node_modules" \
            --exclude="wordpress-svn" \
            ./ wordpress-svn/trunk/

      - name: Commit new version to SVN trunk
        working-directory: wordpress-svn/trunk
        run: |
          svn add --force . --auto-props --parents --depth infinity
          svn st | grep ^! | awk '{print $2}' | xargs -r svn rm

          svn commit -m "Update trunk: ${{ steps.get_info.outputs.message }}" \
            --username "${{ secrets.SVN_USERNAME }}" \
            --password "${{ secrets.SVN_PASSWORD }}" \
            --non-interactive --no-auth-cache

      - name: Create and commit SVN tag
        working-directory: wordpress-svn
        run: |
          svn copy trunk tags/${{ steps.get_info.outputs.tag_name }} \
            -m "Tagging version ${{ steps.get_info.outputs.tag_name }}" \
            --username "${{ secrets.SVN_USERNAME }}" \
            --password "${{ secrets.SVN_PASSWORD }}" \
            --non-interactive --no-auth-cache
  